
rir_base_dir = "Active Acoustics Review/Generated AAES RIRs/";
reverberator_base_dir = "Active Acoustics Review/Reverberators/";
output_base_dir = "Active Acoustics Review/AAES Receiver RIRs/";
bit_depth = 32;

conditions = readmatrix("Active Acoustics Review/SimulationConditions.dat");

for row = [3]%size(conditions, 1)
    rir_set_index = conditions(row, 1);
    num_mics = conditions(row, 2);
    num_ls = conditions(row, 3);
    rev_index = conditions(row, 4);
    loop_gain = -6;%conditions(row, 5);

    % Use this for relative loop gains:
    GenerateAAESIRs(rir_base_dir + "Room Condition " + rir_set_index + "/", ...
        reverberator_base_dir + "Reverberator " + rev_index + "/", ...
        output_base_dir + "AAES Condition " + row + " -6 dB/", ...
        loop_gain, ...
        num_ls, ...
        num_mics, ...
        bit_depth, ...
        true);

    % Use this for absolute loop gains:
    % loop_gain = -49;
    % GenerateAAESIRs(rir_base_dir + "Room Condition " + rir_set_index + "/", ...
    %     reverberator_base_dir + "Reverberator " + rev_index + "/", ...
    %     output_base_dir + "AAES Condition " + row + " -68 dBFS/", ...
    %     loop_gain, ...
    %     num_ls, ...
    %     num_mics, ...
    %     bit_depth, ...
    %     true, ...
    %     false, ...
    %     false);
end