
rir_base_dir = "Active Acoustics Review/Generated AAES RIRs Stimulus Test/";
reverberator_base_dir = "Active Acoustics Review/Reverberators/";
output_base_dir = "Active Acoustics Review/AAES Receiver RIRs/Stimulus Test/";

conditions = readmatrix("Active Acoustics Review/SimulationConditions.dat");

for row = 1
    rir_set_index = conditions(row, 1);
    num_mics = conditions(row, 2);
    num_ls = conditions(row, 3);
    rev_index = conditions(row, 4);
    loop_gain = conditions(row, 5);

    GenerateAAESIRs(rir_base_dir + "Room Condition " + rir_set_index + "/", ...
        reverberator_base_dir + "Reverberator " + rev_index + "/", ...
        output_base_dir + "AAES Condition " + row + "/", ...
        loop_gain, ...
        num_ls, ...
        num_mics, ...
        true, ...
        true);
end